-- 11_relationships.sql — seo_entity_relationships (SmileScape, Wave 1 backfill 2026-07-09).
-- 263 unique edges from content-plan/relationships.md (DR-012 -> DR-013 vocab map: gen_relationships.py).
-- Single idempotent statement: joins skip missing endpoints (reported via missing_list), NOT EXISTS dedups.
with src(from_fp, to_fp, edge_type, note) as (values
('dental-implant','single-tooth-implant','broader_than',NULL),
('dental-implant','multiple-implants','broader_than',NULL),
('dental-implant','implant-supported-bridge','broader_than',NULL),
('dental-implant','overdenture','broader_than',NULL),
('dental-implant','all-on-x','broader_than','Full-arch subset of implant treatment'),
('all-on-x','all-on-4','broader_than',NULL),
('all-on-x','all-on-6','broader_than',NULL),
('all-on-x','zygomatic-implant','broader_than','Extreme bone-loss variant anchored in zygomatic bone'),
('dental-implant','blue-diamond-implant','broader_than','SmileScape-specific signature system — Korean origin'),
('dental-implant','neodent-implant','broader_than','Brazil — Straumann Group subsidiary, GM connection'),
('dental-implant','straumann-implant','broader_than',NULL),
('dental-implant','titanium-implant','broader_than','Material-defined subtype'),
('dental-implant','ceramic-implant','broader_than','Metal-free subtype'),
('guided-bone-regeneration','sausage-technique','broader_than','Specific horizontal/vertical protocol by Dr. Urban'),
('guided-bone-regeneration','ridge-augmentation','broader_than',NULL),
('guided-bone-regeneration','vertical-bone-augmentation','broader_than',NULL),
('bone-grafting','sinus-lift','broader_than',NULL),
('bone-grafting','socket-preservation','broader_than',NULL),
('tooth-loss','edentulism','broader_than','Severity escalation — partial to complete'),
('tooth-loss','dental-caries-extraction','broader_than','Aetiological subtype'),
('tooth-loss','traumatic-tooth-loss','broader_than','Aetiological subtype'),
('tooth-loss','denture-dissatisfaction','broader_than','Outcome state driving implant upgrade'),
('alveolar-bone-loss','vertical-bone-deficiency','broader_than',NULL),
('alveolar-bone-loss','horizontal-bone-deficiency','broader_than',NULL),
('alveolar-bone-loss','maxillary-sinus-proximity','broader_than','Upper-jaw manifestation'),
('gingivitis','periodontitis','broader_than','Disease progression — untreated gingivitis advances to perio'),
('dental-veneer','porcelain-veneer','broader_than',NULL),
('dental-crown','zirconia-crown','broader_than',NULL),
('soft-tissue-management','gum-contouring','broader_than',NULL),
('soft-tissue-management','connective-tissue-graft','broader_than',NULL),
('clear-aligner','trioclear-aligner','broader_than','Brand-specific system offered by SmileScape'),
('peri-implant-mucosa','keratinized-mucosa','broader_than',NULL),
('tooth-extraction','wisdom-tooth-removal','broader_than',NULL),
('smilescape-dental-clinic','lifetime-implant-warranty','broader_than','Brand program'),
('peri-implantitis','periodontitis','is_a','Implant-specific variant — similar bacterial aetiology, different anatomical site'),
('dental-implant','tooth-loss','treats','Hero treatment for hero condition'),
('all-on-x','edentulism','treats','Fixed full-arch solution'),
('all-on-x','denture-dissatisfaction','treats','Upgrade path from removable denture'),
('overdenture','edentulism','treats','More affordable implant-retained full-arch option'),
('guided-bone-regeneration','alveolar-bone-loss','treats','Gold standard for horizontal and vertical defects'),
('sausage-technique','horizontal-bone-deficiency','treats','Primary indication'),
('sausage-technique','vertical-bone-deficiency','treats','Urban protocol — 5.5mm mean gain (P2-C2)'),
('bone-grafting','alveolar-bone-loss','treats','Umbrella bone augmentation'),
('sinus-lift','maxillary-sinus-proximity','treats','Creates vertical bone depth for upper jaw implants'),
('zygomatic-implant','alveolar-bone-loss','treats','Extreme atrophy — bypasses maxillary alveolar bone'),
('clear-aligner','malocclusion','treats',NULL),
('damon-system','malocclusion','treats',NULL),
('connective-tissue-graft','gum-recession','treats',NULL),
('gum-contouring','gum-recession','treats','Aesthetic correction of gum line'),
('root-canal-treatment','dental-caries-extraction','treats','Prevents need for extraction when pulp is still viable'),
('gum-recession','periodontitis','symptom_of','Common sequela of untreated periodontal disease'),
('alveolar-bone-loss','periodontitis','symptom_of','Bone destruction is hallmark of periodontal pathology'),
('tooth-loss','periodontitis','symptom_of','End-stage periodontitis leads to tooth loss'),
('dental-implant','titanium','related_to','[uses] Standard biocompatible implant material'),
('guided-surgery','surgical-guide','related_to','[uses] Guide enables accurate implant positioning'),
('flapless-surgery','surgical-guide','related_to','[uses] Guide required for safe flapless approach'),
('digital-implant-planning','cbct-3d-scan','related_to','[uses] CBCT volumetric data feeds planning software'),
('digital-implant-planning','surgical-guide','related_to','[uses] Planning output generates printed surgical guide'),
('guided-bone-regeneration','ptfe-membrane','related_to','[uses] Non-resorbable barrier — gold standard for GBR'),
('guided-bone-regeneration','bone-graft-substitute','related_to','[uses] Void-filling augmentation material'),
('sausage-technique','ptfe-membrane','related_to','[uses] Urban protocol specifies non-resorbable membrane'),
('sausage-technique','bone-graft-substitute','related_to','[uses]'),
('bone-grafting','prf-platelet-rich-fibrin','related_to','[uses] Autologous growth factor concentrate — accelerates healing'),
('ceramic-implant','zirconia','related_to','[uses] Material-defining property'),
('zirconia-crown','zirconia','related_to','[uses]'),
('digital-smile-design','intraoral-scanner','related_to','[uses] Digital impression feeds DSD workflow'),
('cad-cam','intraoral-scanner','related_to','[uses]'),
('all-on-x','full-arch-immediate-loading','related_to','[uses] Same-day teeth delivery defines All-on-X clinical protocol'),
('dental-implant','removable-denture','related_to','[alternative_to] Gold standard fixed vs interim removable solution'),
('all-on-x','overdenture','related_to','[alternative_to] Fixed full-arch vs removable implant-retained'),
('root-canal-treatment','tooth-extraction','related_to','[alternative_to] Save vs remove — treatment planning decision'),
('ceramic-implant','titanium-implant','related_to','[alternative_to] Metal-free vs standard titanium'),
('clear-aligner','damon-system','related_to','[alternative_to] Removable vs fixed orthodontics'),
('porcelain-veneer','dental-crown','related_to','[alternative_to] Minimal tooth prep vs full crown coverage'),
('immediate-implant','socket-preservation','related_to','[alternative_to] Same-day implant vs staged bone preservation'),
('alveolar-bone','mandible','part_of','Tooth-bearing segment of lower jaw'),
('alveolar-bone','maxilla','part_of','Tooth-bearing segment of upper jaw'),
('maxillary-sinus','maxilla','part_of','Air space limiting implant depth in upper jaw'),
('dental-implant-components','dental-implant','part_of','3-part system: fixture + abutment + crown'),
('smile-dna','smilescape-dental-clinic','part_of','Brand values framework'),
('family-standard','smilescape-dental-clinic','part_of','Ethical operating philosophy'),
('smilescape-rattanathibet','smilescape-dental-clinic','part_of','Physical branch — รัตนาธิเบศร์ (นนทบุรี)'),
('smilescape-srinakarin','smilescape-dental-clinic','part_of','Physical branch — ศรีนครินทร์ (กรุงเทพฯ)'),
('dental-implant','cbct-3d-scan','requires','[requires_assessment] CBCT mandatory before implant planning'),
('all-on-x','cbct-3d-scan','requires','[requires_assessment]'),
('sinus-lift','maxillary-sinus-proximity','requires','[requires_assessment] Condition assessment determines sinus lift need'),
('sausage-technique','horizontal-bone-deficiency','requires','[requires_assessment] Bone volume assessment determines technique eligibility'),
('ortho-implant-sequencing','malocclusion','requires','[requires_assessment] Orthodontic assessment required before sequencing plan'),
('dental-implant','osseointegration','related_to','[evidenced_by] Biological mechanism underpins 96.4% 10-yr survival data (P1-C1 Howe 2019)'),
('sausage-technique','vertical-bone-augmentation','related_to','[evidenced_by] Urban VBA studies (P2-C2, P2-C3) form the protocol evidence base'),
('osseodensification','densah-bur','related_to','[evidenced_by] Densah Bur is the physical instrument enabling Osseodensification mechanism (Huwais authority)'),
('internal-sinus-lift','osseodensification','related_to','[evidenced_by] Crestal sinus elevation via densification — minimally invasive evidence base'),
('vertical-bone-augmentation','rpm-membrane','related_to','[evidenced_by] RPM Membrane enables space maintenance in vertical reconstruction'),
('strip-graft','soft-tissue-management','related_to','[evidenced_by] Urban-attested keratinized tissue technique'),
('ice-berg-technique','soft-tissue-management','related_to','[evidenced_by] Urban-attested gingival thickness technique'),
('garage-technique','soft-tissue-management','related_to','[evidenced_by] Urban-attested papilla preservation technique'),
('dr-woraphat-jarangkul','sausage-technique','related_to','Trained directly by Dr. Urban (HU Berlin)'),
('dr-woraphat-jarangkul','soft-tissue-management','related_to','Trained by Dr. Ricardo Kern (ILAPEO, Brazil)'),
('dr-woraphat-jarangkul','smilescape-dental-clinic','related_to','Medical Director'),
('lifetime-implant-warranty','blue-diamond-implant','related_to','Warranty program covers Blue Diamond system'),
('ortho-implant-sequencing','dental-implant','related_to','Interdisciplinary combo — SmileScape differentiator'),
('peri-implantitis','keratinized-mucosa','related_to','Adequate KM band reduces peri-implantitis risk'),
('smile-dna','family-standard','related_to','Both encode brand philosophy — complementary frameworks'),
('periodontitis','alveolar-bone-loss','related_to','Mutual causation — perio destroys bone; bone loss worsens perio'),
('denture-dissatisfaction','removable-denture','related_to','Dissatisfaction arises from denture limitations'),
('digital-smile-design','dental-veneer','related_to','DSD commonly used in veneer treatment planning'),
('blue-diamond-implant','neodent-implant','related_to','Value-premium implant systems — Asia/LATAM dental tourism evidence category'),
('neodent-implant','straumann-implant','related_to','Neodent is Straumann Group subsidiary — research pipeline + GM Connection shared'),
('dr-woraphat-jarangkul','osseodensification','related_to','Versah training / Huwais workshop (pending operator confirmation)'),
('dr-woraphat-jarangkul','strip-graft','related_to','Trained directly by Dr. Urban — Strip Graft technique'),
('dr-woraphat-jarangkul','ice-berg-technique','related_to','Trained directly by Dr. Urban — Ice Berg/Cube technique'),
('dr-woraphat-jarangkul','garage-technique','related_to','Trained directly by Dr. Urban — Garage technique'),
('densah-bur','smilescape-dental-clinic','related_to','Signature Offering #5 anchor — SmileScape brand-specific tool'),
('black-triangle','gum-recession','related_to','Both are recession-related aesthetic concerns — link Section 5.11 concerns'),
('pediatric-dentistry','early-orthodontic-intervention','related_to','Pediatric → interceptive ortho commonly co-managed'),
('endodontist','apicoectomy','related_to','Surgical endo specialty subset (R27: was cluster-slug endodontics-specialist → entity endodontist)'),
('dental-anxiety','conscious-sedation','related_to','Anxiety = primary indication for sedation referral'),
('dental-anxiety','ga-dentistry','related_to','Severe phobia → GA dentistry pathway'),
('pediatric-dentistry','pediatric-pulpotomy','broader_than',NULL),
('pediatric-dentistry','pediatric-crown','broader_than',NULL),
('pediatric-dentistry','fluoride-treatment','broader_than',NULL),
('pediatric-dentistry','pit-fissure-sealant','broader_than',NULL),
('pediatric-dentistry','space-maintainer','broader_than',NULL),
('pediatric-dentistry','habit-appliance','broader_than',NULL),
('pediatric-dentistry','early-orthodontic-intervention','broader_than',NULL),
('pediatric-dentistry','pediatric-extraction','broader_than',NULL),
('tooth-extraction','pediatric-extraction','broader_than','Pediatric variant — primary teeth'),
('root-canal-treatment','root-canal-retreatment','broader_than',NULL),
('root-canal-treatment','apicoectomy','broader_than','Surgical endo subset'),
('root-canal-treatment','internal-bleaching','broader_than','Post-endo cosmetic'),
('root-canal-treatment','pulp-regeneration','broader_than','Emerging endo subset'),
('conscious-sedation','iv-sedation','broader_than','Moderate variant'),
('internal-sinus-lift','densah-bur','related_to','[uses] Crestal approach with bone densification'),
('guided-bone-regeneration','rpm-membrane','related_to','[uses] Vertical GBR uses RPM (alongside PTFE)'),
('apicoectomy','endodontic-microscope','related_to','[uses] Standard-of-care: microscope-assisted apical surgery'),
('root-canal-treatment','rotary-endodontic-system','related_to','[uses] Modern endo uses rotary files'),
('root-canal-treatment','endodontic-microscope','related_to','[uses] Specialist-tier endo treatment'),
('ga-dentistry','iv-sedation','related_to','[uses] GA pathway often begins with IV induction'),
('airflow-air-polishing','dental-filling','related_to','[uses] Air polishing used pre-restoration (cleaning)'),
('cool-light-whitening-unit','teeth-whitening','related_to','[uses] Device used in in-office whitening procedure'),
('orthognathic-surgery','malocclusion','treats','Skeletal Class II/III + asymmetry'),
('pediatric-pulpotomy','dental-caries-extraction','treats','Saves primary tooth from extraction (parent edge)'),
('apicoectomy','peri-implantitis','treats','Edge: peri-apical lesion treatment (loosely related to peri-implantitis pathology — clinical bridge)'),
('root-canal-retreatment','cracked-tooth','treats','Sometimes; when crack involves canal'),
('internal-bleaching','cracked-tooth','treats','Post-trauma discoloration'),
('caf','gum-recession','treats','Gold standard root coverage'),
('tunneling-technique','gum-recession','treats',NULL),
('vista-technique','gum-recession','treats','Multiple-tooth recession'),
('tcaf','gum-recession','treats','Hybrid root coverage'),
('strip-graft','gum-recession','treats','Keratinized augmentation + indirect root coverage'),
('vipct','black-triangle','treats','Papilla regeneration approach'),
('conscious-sedation','dental-anxiety','treats','Mild anxiety pathway'),
('ga-dentistry','dental-anxiety','treats','Severe phobia pathway'),
('internal-sinus-lift','sinus-lift','is_a','Crestal/transalveolar approach variant'),
('lateral-window-sinus-lift','sinus-lift','is_a','Traditional lateral approach'),
('neodent-implant','straumann-implant','is_a','Subsidiary brand within Straumann Group'),
('passive-self-ligating','damon-system','is_a','PSL is the design class of Damon brackets'),
('acteon-cbct','cbct-3d-scan','part_of','Brand instance of CBCT category'),
('trios-intraoral-scanner','intraoral-scanner','part_of','Brand instance of IOS category'),
('zero-bone-loss-concept','dr-tomas-linkevicius','related_to','[evidenced_by] Authority anchor — Linkevicius 2009+ research + 2019 Quintessence textbook'),
('zero-bone-loss-concept','dental-implant','related_to','ZBL = how SmileScape does implants (philosophy/protocol)'),
('zero-bone-loss-concept','lifetime-implant-warranty','related_to','Zero bone loss = warranty validity foundation'),
('zero-bone-loss-concept','keratinized-mucosa','related_to','ZBL requires ≥2mm keratinized tissue around implant'),
('zero-bone-loss-concept','smile-dna','related_to','Brand triad: SMILE DNA (values) + Family Standard (ethics) + ZBL (clinical protocol)'),
('zero-bone-loss-concept','family-standard','related_to','Brand triad complement'),
('dr-woraphat-jarangkul','zero-bone-loss-concept','related_to','Practitioner of ZBL protocol (pending Linkevicius training credential confirm)'),
('dr-woraphat-jarangkul','dr-tomas-linkevicius','related_to','External authority/mentor reference (pending operator confirmation)'),
('airflow-air-polishing','zero-bone-loss-concept','related_to','[uses] GBT + Airflow = ZBL maintenance protocol component'),
('peri-implantitis-treatment','peri-implantitis','treats','Service entity treats condition entity'),
('peri-implantitis-treatment','implantoplasty','broader_than',NULL),
('peri-implantitis-treatment','regenerative-peri-implantitis-surgery','broader_than',NULL),
('peri-implantitis-treatment','resective-peri-implantitis-surgery','broader_than',NULL),
('peri-implantitis-treatment','dental-laser-therapy','related_to','[uses] Laser-assisted decontamination'),
('regenerative-peri-implantitis-surgery','guided-bone-regeneration','related_to','[uses] GBR principles applied to peri-implant defects'),
('regenerative-peri-implantitis-surgery','rpm-membrane','related_to','[uses] Space maintenance for peri-implant defects'),
('peri-implantitis','periodontitis','symptom_of','Shared pathophysiology — bacterial biofilm'),
('zero-bone-loss-concept','peri-implantitis','related_to','ZBL prevents peri-implantitis via maintenance protocol'),
('gold-crown','dental-crown','is_a','Material variant of dental crown'),
('gold-crown','zirconia-crown','related_to','[alternative_to] Premium crown material decision tree'),
('direct-print-clear-aligner','clear-aligner','is_a','Direct Print = clear-aligner subtype'),
('direct-print-clear-aligner','thermoformed-aligner','related_to','[alternative_to] Direct Print vs Thermoformed — comparison content anchor'),
('direct-print-clear-aligner','trioclear-aligner','related_to','[alternative_to] In-house Direct Print vs outsourced TrioClear'),
('direct-print-clear-aligner','photopolymer-resin-tc85','related_to','[uses] TC-85DAC / Tera Harz material'),
('direct-print-clear-aligner','3d-printer-aligner','related_to','[uses] Asiga / SprintRay / Formlabs printer'),
('direct-print-clear-aligner','in-house-aligner-lab','related_to','Lab capability ties to signature offering'),
('in-house-aligner-lab','smilescape-dental-clinic','related_to','Brand-specific manufacturing capability'),
('in-house-aligner-lab','photopolymer-resin-tc85','related_to','[uses] Material consumption in lab'),
('in-house-aligner-lab','3d-printer-aligner','related_to','[uses] Equipment in lab'),
('aligner-attachment','clear-aligner','related_to','Composite attachment used by thermoformed aligners'),
('aligner-attachment','direct-print-clear-aligner','related_to','[alternative_to] Direct Print uses fewer attachments (built-in features replace) — competitive comparison'),
('direct-print-clear-aligner','malocclusion','treats','Service treats condition'),
('direct-print-clear-aligner','smilescape-dental-clinic','related_to','Signature offering brand anchor'),
('dr-woraphat-jarangkul','direct-print-clear-aligner','related_to','Medical Director oversees in-house lab (R11 — operator confirm role)'),
('geriatric-dentistry','bedridden-dentistry','broader_than','Sub-service for immobile patients'),
('medical-compromised-dentistry','medical-clearance-protocol','related_to','[uses] Pre-op screening required'),
('special-needs-dentistry','ga-dentistry','related_to','Often paired with GA/sedation'),
('geriatric-dentistry','xerostomia','related_to','Senior + dry mouth comorbid'),
('geriatric-dentistry','root-caries','related_to','Senior caries risk'),
('geriatric-dentistry','removable-denture','related_to','Common senior prosthetic'),
('geriatric-dentistry','overdenture','related_to','Implant-retained option for senior'),
('pregnancy-dental-care','pregnancy-gingivitis','related_to','Service treats hormonal gingivitis'),
('pregnancy-dental-care','pregnancy-gingivitis','treats','Direct treatment relationship'),
('medical-compromised-dentistry','dental-implant','related_to','High-stakes risk assessment for implant patients'),
('medical-compromised-dentistry','conscious-sedation','related_to','Often required for comorbid patients'),
('medical-compromised-dentistry','dental-implant','requires','[requires_assessment] MRONJ + cardiac + diabetes screening before implant placement'),
('medical-clearance-protocol','tooth-extraction','requires','[requires_assessment] Pre-op for Bisphosphonate patients (MRONJ risk)'),
('geriatric-dentistry','smilescape-dental-clinic','related_to','Demographic service positioning'),
('special-needs-dentistry','family-standard','related_to','Brand ethics fit: care like family'),
('medical-compromised-dentistry','smilescape-dental-clinic','related_to','Premium clinic positioning'),
('densah-bur','dr-woraphat-jarangkul','related_to','Pending Versah training credential — brand authority'),
('strip-graft','dr-tomas-linkevicius','related_to','[evidenced_by] P6 cross-reference: Linkevicius also published on keratinized mucosa around implants'),
('peri-implantitis-treatment','peri-implantitis','related_to','[evidenced_by] P9 Schwarz EFP 2018 consensus (PMID 25626479) + 2023 SR (PMID 37271498)'),
('caf','gum-recession','related_to','[evidenced_by] P6 Zucchelli root coverage CAF — gold standard'),
('tunneling-technique','gum-recession','related_to','[evidenced_by] P6 Allen 1994 / Zabalegui 1999 classic'),
('vista-technique','gum-recession','related_to','[evidenced_by] P6 Zadeh 2011 IJPRD original VISTA paper'),
('dental-caries','fluoride-treatment','related_to','[evidenced_by] P15 WHO 2019 + Cochrane Walsh 2019 fluoride'),
('white-spot-lesion','fluoride-treatment','related_to','[evidenced_by] P15 remineralization claim — Tier 1 ADA + WHO'),
('pit-fissure-sealant','dental-caries','related_to','[evidenced_by] P15 Cochrane Ahovuo-Saloranta 2017'),
('dental-abscess','periodontitis','related_to','[evidenced_by] P14 Tonetti 2018 perio classification consensus'),
('dry-socket','tooth-extraction','related_to','[evidenced_by] P14 Cochrane Daly 2012 local interventions SR'),
('pregnancy-gingivitis','gingivitis','related_to','[evidenced_by] P14 hormonal gingivitis hormonal etiology consensus'),
('social-security-dental-benefit','smilescape-dental-clinic','related_to','[evidenced_by] P13 sso.go.th regulatory database — Q-Clinic verification'),
('sso-direct-billing-q-clinic','smilescape-dental-clinic','related_to','[evidenced_by] P13 Q-Clinic certificate (operator pending)'),
('dental-caries','white-spot-lesion','broader_than','Reversible early stage'),
('dental-caries','root-caries','broader_than','Senior subtype'),
('dental-caries','dental-abscess','symptom_of','Untreated decay progresses to abscess'),
('dental-caries','dental-filling','related_to','Treatment relationship'),
('dental-caries','root-canal-treatment','related_to','Deep caries → endo'),
('dental-caries','xerostomia','related_to','Dry mouth = caries risk multiplier'),
('root-caries','gum-recession','related_to','Exposed root + decay'),
('dental-abscess','periodontitis','symptom_of','Acute manifestation'),
('dental-abscess','dental-caries','symptom_of','Pulpal origin variant'),
('dental-abscess','gingivitis','related_to','Acute gingival swelling'),
('pregnancy-gingivitis','gingivitis','is_a','Hormonal variant'),
('pregnancy-gingivitis','conscious-sedation','related_to','Q2 trimester safety considerations'),
('bruxism','tmj-disorder','related_to','Bidirectional causation'),
('bruxism','tooth-fracture','related_to','Wear → fracture'),
('tmj-disorder','malocclusion','related_to','Bite imbalance contribution'),
('bruxism','tooth-fracture','treats','Indirectly via prevention'),
('tooth-fracture','cracked-tooth','broader_than','Cracked = fracture subtype'),
('tooth-fracture','dental-crown','related_to','Crown protection treatment'),
('tooth-fracture','porcelain-veneer','related_to','Aesthetic restoration'),
('dry-socket','tooth-extraction','symptom_of','Post-extraction complication'),
('dry-socket','wisdom-tooth-removal','related_to','Most common after wisdom tooth'),
('halitosis','periodontitis','symptom_of','Perio = #1 cause'),
('halitosis','dental-caries','symptom_of','Deep caries gas'),
('halitosis','xerostomia','symptom_of','Low saliva → bacterial overgrowth'),
('halitosis','airflow-air-polishing','related_to','Tongue/biofilm removal treatment'),
('xerostomia','dental-caries','related_to','Risk multiplier'),
('xerostomia','halitosis','related_to','Bacterial overgrowth'),
('xerostomia','pediatric-dentistry','related_to','Mouth-breathing kids'),
('social-security-dental-benefit','sso-direct-billing-q-clinic','broader_than','Q-Clinic = SSO billing modality variant'),
('sso-direct-billing-q-clinic','smilescape-rattanathibet','related_to','Branch-level direct billing capability'),
('sso-direct-billing-q-clinic','smilescape-srinakarin','related_to','Branch-level direct billing capability'),
('social-security-dental-benefit','dental-filling','related_to','Covered procedure'),
('social-security-dental-benefit','tooth-extraction','related_to','Covered procedure'),
('social-security-dental-benefit','wisdom-tooth-removal','related_to','Covered procedure (simple cases)'),
('social-security-dental-benefit','removable-denture','related_to','Separate cap 1,500-4,400 บาท/5 yr'),
('social-security-dental-benefit','universal-coverage-th','related_to','[alternative_to] Mutually exclusive — patient chooses one'),
('social-security-dental-benefit','civil-servant-dental-benefit','related_to','[alternative_to] Mutually exclusive by employment status'),
('social-security-dental-benefit','private-dental-insurance-th','related_to','[alternative_to] Often stackable — SSO first, private reimburses excess'),
('social-security-dental-benefit','dental-implant','related_to','NOT covered — common upsell pathway from SSO patients'),
('social-security-dental-benefit','clear-aligner','related_to','NOT covered — orthodontic education')),
missing as (
  select distinct fp from (select from_fp fp from src union select to_fp from src) x
  where not exists (select 1 from public.seo_entity_graph g where g.entity_fingerprint = x.fp)),
ins as (
  insert into public.seo_entity_relationships (from_entity_fp, to_entity_fp, edge_type, edge_note, brand_scope)
  select s.from_fp, s.to_fp, s.edge_type, s.note,
    case when '*' = any(f.brand_scope) and '*' = any(t.brand_scope)
         then array['*']::text[] else array['smile-scape-clinic']::text[] end
  from src s
  join public.seo_entity_graph f on f.entity_fingerprint = s.from_fp
  join public.seo_entity_graph t on t.entity_fingerprint = s.to_fp
  where s.from_fp <> s.to_fp
    and not exists (select 1 from public.seo_entity_relationships r
                    where r.from_entity_fp = s.from_fp and r.to_entity_fp = s.to_fp
                      and r.edge_type = s.edge_type)
  returning edge_type, brand_scope)
select (select count(*) from src) src_edges,
       (select count(*) from ins) inserted,
       (select count(*) filter (where brand_scope = array['*']) from ins) universal,
       (select count(*) filter (where brand_scope = array['smile-scape-clinic']) from ins) ss_scoped,
       (select count(*) from missing) missing_endpoints,
       (select string_agg(fp, ', ') from missing) missing_list;
