-- 13_pages_resync.sql — Wave 2b(cont): resync page_name + primary_entity_fp to canonical R26.
-- 127 surviving nodes whose number stayed but content moved (R18-R22 section reorder).
-- Non-destructive UPDATE; node key unchanged. Then re-derive cluster.
with src(fp, name, ent) as (values
('smilescape-2.1.4','The Family Standard — "ถ้าไม่กล้าทำให้พ่อแม่ เราจะไม่ทำคนไข้"','family-standard'),
('smilescape-3.1.5','Digital Smile Design — ออกแบบรอยยิ้มดิจิทัล (→ canonical 3.9.1 Cosmetic DSD)','digital-smile-design'),
('smilescape-3.2.8.3','All-on-4 — ฟันทั้งปากบน 4 ราก (type/info → canonical 3.3 All-on-X)','all-on-4'),
('smilescape-3.2.8.4','All-on-6 — ฟันทั้งปากบน 6 ราก (→ canonical 3.3 All-on-X)','all-on-6'),
('smilescape-3.2.11.1','รากฟันเทียม vs สะพานฟัน — เลือกอะไรดี (→ link 3.5.2 Bridge)','dental-implant'),
('smilescape-3.2.11.2','รากฟันเทียม vs ฟันปลอม — เปรียบเทียบข้อดีข้อเสีย (→ link 3.5.4 Denture)','removable-denture'),
('smilescape-3.3.4','All-on-4 บน vs ล่าง — Upper & Lower Jaw (R21 รวม 2→1: DFS ไม่มี jaw-specific demand)','all-on-4'),
('smilescape-3.3.5','All-on-X สำหรับผู้ที่ใส่ฟันปลอมมานาน (→ link 3.5.4 Denture)','all-on-x'),
('smilescape-3.3.6','All-on-X สำหรับผู้สูงอายุ (→ link 3.13.1 Geriatric hub)','all-on-x'),
('smilescape-3.3.7','วัสดุฟันถาวร All-on-X — Zirconia vs Acrylic vs Hybrid','all-on-x'),
('smilescape-3.3.8','ราคา All-on-X SmileScape — แผนผ่อนชำระ','all-on-x'),
('smilescape-3.3.9','การดูแลหลัง All-on-X — ทำความสะอาดและตรวจเช็ค','all-on-x'),
('smilescape-3.3.10','All-on-X Case Gallery — ผลงานจริง','all-on-x'),
('smilescape-3.4','ทันตกรรมทั่วไป — General Dentistry (hub)','dental-scaling'),
('smilescape-3.4.1','ตรวจฟันและขูดหินปูน — Dental Checkup & Cleaning (hub) 🎯','dental-scaling'),
('smilescape-3.4.2','อุดฟัน — Dental Filling','dental-filling'),
('smilescape-3.4.3','ถอนฟัน — Tooth Extraction','tooth-extraction'),
('smilescape-3.4.4','ผ่าฟันคุด — Wisdom Tooth Removal','wisdom-tooth-removal'),
('smilescape-3.4.4.1','ฟันคุดฝัง — Impacted Wisdom Tooth','wisdom-tooth-removal'),
('smilescape-3.4.4.2','การฟื้นตัวหลังผ่าฟันคุด','wisdom-tooth-removal'),
('smilescape-3.5','ทันตกรรมบูรณะและประดิษฐ์ — Restorative & Prosthetic Dentistry (hub)','dental-crown'),
('smilescape-3.5.1','ครอบฟัน — Dental Crown (hub)','dental-crown'),
('smilescape-3.5.1.1','Zirconia Crown — ครอบฟันเซอร์โคเนีย','zirconia-crown'),
('smilescape-3.5.1.2','E-Max Crown — ครอบฟันอีแมกซ์','dental-crown'),
('smilescape-3.5.1.3','Implant Crown — ครอบฟันบนรากเทียม (→ link 3.2.8 + tech 4.7)','dental-crown'),
('smilescape-3.5.1.4','Gold Crown — ครอบฟันทองคำ','gold-crown'),
('smilescape-3.5.3','Inlay / Onlay — ชิ้นงานเซรามิกเฉพาะจุด','dental-crown'),
('smilescape-3.5.4','ฟันปลอม — Removable Denture (R18 ย้ายจาก General)','removable-denture'),
('smilescape-3.6','รักษารากฟันโดยทันตแพทย์เฉพาะทาง (hub)','root-canal-treatment'),
('smilescape-3.6.1','รักษาคลองรากฟัน — Root Canal Treatment','root-canal-treatment'),
('smilescape-3.6.2','รักษาคลองรากฟันซ้ำ — Endodontic Retreatment','root-canal-retreatment'),
('smilescape-3.6.3','ผ่าตัดปลายราก — Apicoectomy / Surgical Endodontics','apicoectomy'),
('smilescape-3.6.4','รักษารากฟันด้วยกล้องจุลทรรศน์ — Endodontic Microscope','endodontic-microscope'),
('smilescape-3.6.5','เครื่องมือ Rotary / Reciprocating Endodontics','rotary-endodontic-system'),
('smilescape-3.6.6','ฟอกฟันตายภายใน — Internal Bleaching','internal-bleaching'),
('smilescape-3.7.4','เหงือกร่น — Gum Recession Treatment (↔ 3.2.9.7.3 Root Coverage)','gum-recession'),
('smilescape-3.7.7.9','Post-Treatment Maintenance Protocol → link 3.4.1 GBT/Airflow','peri-implantitis-treatment'),
('smilescape-3.8.1','ผ่าตัดฟันคุดซับซ้อน — Complex Impaction (↔ 3.4.4 ฟันคุด routine)','wisdom-tooth-removal'),
('smilescape-3.8.2','ผ่าตัดเนื้องอกในช่องปาก — Oral Pathology','oral-pathology'),
('smilescape-3.8.3','ผ่าตัดซีสต์ — Cyst Removal','oral-pathology'),
('smilescape-3.8.4','Frenectomy — ตัดเนื้อเยื่อยึดลิ้น/ริมฝีปาก (R22 entity fix)','frenectomy'),
('smilescape-3.9','ทันตกรรมเพื่อความสวยงาม — Smile Design (hub)','digital-smile-design'),
('smilescape-3.9.1','Digital Smile Design — ออกแบบรอยยิ้มดิจิทัล','digital-smile-design'),
('smilescape-3.9.2','วีเนียร์ — Dental Veneer (sub-hub)','dental-veneer'),
('smilescape-3.9.3','Teeth Whitening — ฟอกสีฟัน (hub)','teeth-whitening'),
('smilescape-3.9.4','Gum Contouring — ตกแต่งเหงือก (Gummy Smile)','gum-contouring'),
('smilescape-3.9.5','Smile Makeover — แปลงโฉมรอยยิ้มครบวงจร','digital-smile-design'),
('smilescape-3.9.6','ราคาทันตกรรมเพื่อความสวยงาม SmileScape','digital-smile-design'),
('smilescape-3.10','จัดฟัน — Orthodontics at SmileScape (hub)','clear-aligner'),
('smilescape-3.10.1','จัดฟันใส — Clear Aligner Hero (sub-hub)','clear-aligner'),
('smilescape-3.10.3','Self-Ligating Braces — PSL & ASL (hub)','passive-self-ligating'),
('smilescape-3.10.4','จัดฟันเหล็ก — Conventional Braces','orthodontic-treatment'),
('smilescape-3.10.5','จัดฟันผู้ใหญ่ — Orthodontics for Adults','orthodontic-treatment'),
('smilescape-3.10.6','จัดฟันก่อนทำรากฟันเทียม — Ortho + Implant Sequencing','ortho-implant-sequencing'),
('smilescape-3.10.7','ราคาจัดฟัน SmileScape — เปรียบเทียบแต่ละแบบ','orthodontic-treatment'),
('smilescape-3.11','ทันตกรรมเด็ก — Kids Dentistry by SmileScape (hub)','pediatric-dentistry'),
('smilescape-3.11.1','First Dental Visit — ครั้งแรกของลูก (1 ขวบ / ฟันซี่แรก)','pediatric-dentistry'),
('smilescape-3.11.2','ตรวจฟันเด็ก & ขูดหินปูนเด็ก — Pediatric Checkup & Cleaning','pediatric-dentistry'),
('smilescape-3.11.3','อุดฟันน้ำนม — ฟันน้ำนมผุ (Primary Tooth Filling)','dental-filling'),
('smilescape-3.11.4','เคลือบฟลูออไรด์ — Fluoride Treatment','fluoride-treatment'),
('smilescape-3.11.5','เคลือบหลุมร่องฟัน — Pit & Fissure Sealant','pit-fissure-sealant'),
('smilescape-3.11.6','รักษารากฟันน้ำนม — Pulpotomy / Pulpectomy','pediatric-pulpotomy'),
('smilescape-3.11.7','ครอบฟันเด็ก — Stainless Steel Crown / Zirconia Crown','pediatric-crown'),
('smilescape-3.11.8','เครื่องมือกันฟันล้ม — Space Maintainer','space-maintainer'),
('smilescape-3.11.9','ถอนฟันน้ำนม — Primary Tooth Extraction','pediatric-extraction'),
('smilescape-3.12','บริการดมยาสลบทำฟัน — Sedation & GA Dentistry (hub)','ga-dentistry'),
('smilescape-3.12.2','IV Sedation — Moderate Sedation','iv-sedation'),
('smilescape-3.12.3','General Anesthesia — ดมยาสลบทำฟันโดยวิสัญญีแพทย์','ga-dentistry'),
('smilescape-3.12.5','ขั้นตอนและความปลอดภัย — Anesthesiologist on-site','ga-dentistry'),
('smilescape-3.13.1.3','Implant สำหรับผู้สูงอายุ — เคสซับซ้อน (→ link 3.2.10.2)','dental-implant'),
('smilescape-3.13.1.4','ปากแห้ง + อาหารแข็งไม่ได้ (→ link 5.18)','xerostomia'),
('smilescape-3.14.1','ขั้นตอน "ไม่ต้องสำรองจ่าย" ที่ SmileScape Q-Clinic','sso-direct-billing-q-clinic'),
('smilescape-4.2','เทคโนโลยีวินิจฉัย (hub) — Service → 3.1 Precision Diagnostics','cbct-3d-scan'),
('smilescape-4.3','เทคโนโลยีวางแผนรากฟันเทียม (hub) — Service → 3.1.4 Digital Planning / 3.2.5 ขั้นตอน','dental-implant'),
('smilescape-4.5','ระบบรากฟันเทียม SmileScape (hub) — Service → 3.2.11.6 เปรียบเทียบแบรนด์','dental-implant'),
('smilescape-4.5.4','Ceramic (Zirconia) Implant System — ระบบรากเทียมเซรามิกไร้โลหะ (R23 entity fix → service 3.2.8.11)','ceramic-implant'),
('smilescape-4.5.7','Connection Types — ระบบเชื่อมต่อรากฟันเทียม-Abutment (Internal vs External)','dental-implant'),
('smilescape-4.6.0.3','Direct Print Workflow — Digital Scan → Plan → Print → Polish → Deliver (incl. fewer-attachments + same-day — R16 folded จาก 3.10.1.5/.6)','direct-print-clear-aligner'),
('smilescape-4.6.0.6','Direct Print vs Thermoformed Aligner — Method Comparison (R16 ย้ายจาก 3.10.1.4)','thermoformed-aligner'),
('smilescape-4.7','เทคโนโลยีครอบฟันและชิ้นงานบนรากเทียม (hub) — Service → 3.5 Restorative & Prosthetic (R23 DR-002, deferred from R18)','dental-crown'),
('smilescape-4.7.3','Hybrid Prosthesis — ชิ้นงานไฮบริดสำหรับ All-on-X (→ service 3.3 All-on-X)','all-on-x'),
('smilescape-4.9.1','Cool Light Whitening Unit — เครื่องฟอกสีฟันด้วยแสง LED เย็น (Service → 3.9.3.1 Cool Light Whitening)','cool-light-whitening-unit'),
('smilescape-5.4.4','กลัวหมอฟัน (Dental Phobia) — วิธีเอาชนะความกลัว','dental-anxiety'),
('smilescape-5.6.1','ปวดฟัน — สาเหตุและวิธีรักษา','dental-caries'),
('smilescape-5.6.2.2','ฟันผุลึกถึงเนื้อในฟัน — Pulpitis (→ link 3.6)','dental-caries'),
('smilescape-5.6.2.4','ป้องกันฟันผุ — Fluoride + Sealant + Diet (→ 3.11.4 + 3.11.5)','fluoride-treatment'),
('smilescape-5.6.5','ฟันร้าว — อาการและการรักษา (→ 5.16 + 3.6.7)','cracked-tooth'),
('smilescape-5.8.1','ทำฟันผู้สูงอายุ — สิ่งที่ต้องรู้','geriatric-dentistry'),
('smilescape-5.8.2','ทำฟันผู้ป่วยเบาหวาน','medical-compromised-dentistry'),
('smilescape-5.8.3','ทำฟันหญิงตั้งครรภ์','pregnancy-dental-care'),
('smilescape-5.8.4','ทำฟันผู้ป่วยโรคหัวใจ','medical-compromised-dentistry'),
('smilescape-5.8.5','ทำฟันผู้ป่วยที่กินยาละลายลิ่มเลือด','medical-compromised-dentistry'),
('smilescape-5.8.6','ผู้ป่วยมะเร็ง + ทำฟัน — ก่อน/ระหว่าง/หลังเคมีบำบัด (R5)','medical-compromised-dentistry'),
('smilescape-5.8.7','ผู้ป่วยภูมิคุ้มกันต่ำ — Immunocompromised Dentistry (R5)','medical-compromised-dentistry'),
('smilescape-5.8.8','ผ่าตัดเปลี่ยนข้อเข่า / สะโพก — Antibiotic Prophylaxis (R5)','medical-compromised-dentistry'),
('smilescape-5.8.9','ผู้ป่วยกินยา Bisphosphonate (Osteoporosis) — MRONJ Risk ⚠️ (R5)','medical-compromised-dentistry'),
('smilescape-5.8.10','ผู้ป่วยรับรังสีรักษา (Head & Neck Radiation) — ORN Risk (R5)','medical-compromised-dentistry'),
('smilescape-5.8.11','ผู้ป่วยตับ / ไต — Renal & Hepatic considerations (R5)','medical-compromised-dentistry'),
('smilescape-5.10.7','คางยื่น / คางหด — แก้ด้วยจัดฟันหรือผ่าตัด (→ link 3.10.8 Orthognathic)','orthognathic-surgery'),
('smilescape-5.10.9','จัดฟันใส attachment น้อย — Direct Print Aligner (R16 — → link 3.10.1.1 In-House / tech 4.6.0)','direct-print-clear-aligner'),
('smilescape-5.11.8','เหงือกไม่เท่ากัน / สูงต่ำไม่สมมาตร (Gingival Asymmetry) (→ link 3.2.9.7 + 3.9.4)','gum-contouring'),
('smilescape-5.12.1','ฟันน้ำนมผุ — ต้องอุดหรือปล่อย','dental-caries'),
('smilescape-5.12.2','ฟันแท้ซ้อนฟันน้ำนม — ต้องถอนไหม','pediatric-dentistry'),
('smilescape-5.12.3','ฟันเด็กขึ้นช้า / ไม่ขึ้น — เมื่อไหร่ต้องพบหมอ','pediatric-dentistry'),
('smilescape-5.12.4','เด็กกลัวหมอฟัน — วิธีเตรียมลูกก่อนพาไปทำฟัน','pediatric-dentistry'),
('smilescape-5.12.6','นิสัยดูดนิ้ว / อมจุกนม — ส่งผลต่อฟันอย่างไร','pediatric-dentistry'),
('smilescape-5.13.2.2','ขูดหินปูน / อุดฟัน / ถอนฟัน ใช้ประกันสังคม (→ link 3.4.1.7)','social-security-dental-benefit'),
('smilescape-5.13.2.10','คลินิกทำฟัน "ไม่ต้องสำรองจ่าย" (Q-Clinic) คืออะไร (DFS hot) (→ link 3.14.1)','sso-direct-billing-q-clinic'),
('smilescape-5.14.6','เด็กปวดฟันคืนนี้ — Pediatric Emergency (→ link 3.11)','pediatric-dentistry'),
('smilescape-5.16.4','ฟันร้าว — Cracked Tooth Syndrome (→ link 3.6.7)','cracked-tooth'),
('smilescape-5.17.6','กลิ่นปากจากรากฟันอักเสบ (→ link 3.6)','root-canal-treatment'),
('smilescape-6.2.5.2','Invisalign คืออะไร — ข้อดีข้อเสีย ราคา เหมาะกับใคร (R16 → service 3.10.1.3 Thermoformed)','clear-aligner'),
('smilescape-6.2.5.8','Direct Print Clear Aligner คืออะไร — เทคโนโลยีพิมพ์ 3D ตรง (R11 — educational; → tech 4.6.0)','direct-print-clear-aligner'),
('smilescape-6.2.5.9','Photopolymer Resin TC-85 — Material properties + Safety (R11 — → tech 4.6.0.2)','photopolymer-resin-tc85'),
('smilescape-6.5.1.3','FAQ จัดฟัน (15+) — ← link from 3.10','clear-aligner'),
('smilescape-6.5.1.4','FAQ วีเนียร์และครอบฟัน — ← link from 3.9 (วีเนียร์) + 3.5 (ครอบฟัน, R18)','dental-veneer'),
('smilescape-6.5.1.5','FAQ ทันตกรรมเด็ก — ← link from 3.11','pediatric-dentistry'),
('smilescape-6.5.1.6','FAQ Endodontics / รักษารากฟัน — ← link from 3.6','root-canal-treatment'),
('smilescape-6.5.1.7','FAQ Sedation / ดมยาสลบทำฟัน — ← link from 3.12','ga-dentistry'),
('smilescape-6.5.3.3','FAQ เด็ก (→ link 5.12 + 3.11)','pediatric-dentistry'),
('smilescape-7.2.8','Case: Implant + Soft Tissue Graft — เคสปลูกเหงือก','soft-tissue-management'),
('smilescape-7.5.3','Case: จัดฟันใส Invisalign (R16 → service 3.10.1.3)','clear-aligner'),
('smilescape-7.6.1','เรื่องราวคนไข้: "ไม่เคยยิ้มมา 10 ปี ตอนนี้ยิ้มทุกวัน"','smilescape-dental-clinic'),
('smilescape-7.6.2','เรื่องราวคนไข้: "จากฟันปลอมหลวมสู่ All-on-4"','all-on-4'),
('smilescape-7.6.3','เรื่องราวคนไข้: "กลัวหมอฟันมาก แต่ที่นี่ทำให้สบายใจ"','smilescape-dental-clinic'),
('smilescape-7.6.4','เรื่องราวคนไข้: "ทำรากเทียมตอนอายุ 72 ก็ยังได้"','smilescape-dental-clinic'),
('smilescape-7.6.5','เรื่องราวคนไข้: "เคยทำที่อื่นล้มเหลว มาแก้ไขที่ SmileScape"','smilescape-dental-clinic'))
update public.seo_website_page_master p set page_name = src.name, primary_entity_fp = src.ent
from src where p.page_fingerprint = src.fp;

update public.seo_website_page_master p set cluster_id = g.topic_cluster_id
  from public.seo_entity_graph g
  where p.brand_id='smile-scape-clinic' and p.primary_entity_fp is not null
    and g.entity_fingerprint = p.primary_entity_fp
    and p.cluster_id is distinct from g.topic_cluster_id;

select count(*) total,
  count(*) filter (where not exists (select 1 from seo_entity_graph g where g.entity_fingerprint=p.primary_entity_fp)) orphan_entity,
  count(cluster_id) with_cluster
from public.seo_website_page_master p where page_fingerprint like 'smilescape-%';
