-- 21_page_cluster_remap.sql — Wave 11: put SmileScape's pages back on SmileScape's OWN clusters. 2026-07-16.
--
-- WHY (collision audit, Phase 2 finding):
--   SmileScape's entities.md defines 168 entities across ITS OWN 20-cluster taxonomy
--   (dental-implant-core / patient-conditions-bone / smile-design-cosmetic / ...).
--   51 of those entities already existed — created by DEEZY, whose taxonomy is different
--   (implant-dentistry / preventive-general / cosmetic-dentistry / ...). 01_entities.sql used
--   ON CONFLICT DO NOTHING, so Deezy's topic_cluster_id survived; then 06_pages.sql did
--   `page.cluster_id = entity.topic_cluster_id` → **387 of 722 SmileScape pages (54%) inherited
--   DEEZY's clusters** (implant-dentistry 161, orthodontics 43, preventive-general 36, ...).
--   That broke per-brand cluster health / topical authority / hub-spoke + cluster_spoke link roles.
--
-- ROOT CAUSE (structural, not a load bug): `topic_cluster_id` is a SINGLE field on a SHARED entity,
--   so one entity can only ever sit in one brand's cluster — whoever loads second always loses.
--   Proper fix is a per-brand cluster junction (entity × brand → cluster) — raised to protocol, NOT done here.
--
-- WHAT THIS DOES (operator-approved option B): sets page.cluster_id from SmileScape's OWN authored
--   entity→cluster map (content-plan/entities.md section headers) instead of reading it off the shared
--   entity row. Touches ONLY smilescape-% pages. Does NOT modify any entity, Deezy or VTH row.
--   Reversible. All 20 SS cluster slugs verified present in seo_topic_cluster_master; cluster_id has no FK.
--   NB `pediatric-dentistry` is a genuinely shared slug (Deezy created the row, same name/meaning).
--
-- RESULT: pages on SS clusters 335 → 722/722 · foreign 387 → 0 · null 0.
with ssmap(fp, ss_cluster) as (values
  ('dental-implant','dental-implant-core'),
  ('single-tooth-implant','dental-implant-core'),
  ('multiple-implants','dental-implant-core'),
  ('immediate-implant','dental-implant-core'),
  ('immediate-loading','dental-implant-core'),
  ('osseointegration','dental-implant-core'),
  ('flapless-surgery','dental-implant-core'),
  ('guided-surgery','dental-implant-core'),
  ('implant-supported-bridge','dental-implant-core'),
  ('blue-diamond-implant','implant-systems-brands'),
  ('neodent-implant','implant-systems-brands'),
  ('straumann-implant','implant-systems-brands'),
  ('ceramic-implant','implant-systems-brands'),
  ('titanium-implant','implant-systems-brands'),
  ('guided-bone-regeneration','bone-regeneration-gbr'),
  ('sausage-technique','bone-regeneration-gbr'),
  ('bone-grafting','bone-regeneration-gbr'),
  ('sinus-lift','bone-regeneration-gbr'),
  ('ridge-augmentation','bone-regeneration-gbr'),
  ('socket-preservation','bone-regeneration-gbr'),
  ('vertical-bone-augmentation','bone-regeneration-gbr'),
  ('rpm-membrane','bone-regeneration-gbr'),
  ('densah-bur','bone-regeneration-gbr'),
  ('osseodensification','bone-regeneration-gbr'),
  ('internal-sinus-lift','bone-regeneration-gbr'),
  ('lateral-window-sinus-lift','bone-regeneration-gbr'),
  ('all-on-x','all-on-x-full-arch'),
  ('all-on-4','all-on-x-full-arch'),
  ('all-on-6','all-on-x-full-arch'),
  ('full-arch-immediate-loading','all-on-x-full-arch'),
  ('overdenture','all-on-x-full-arch'),
  ('zygomatic-implant','all-on-x-full-arch'),
  ('tooth-loss','patient-conditions-tooth-loss'),
  ('edentulism','patient-conditions-tooth-loss'),
  ('dental-caries-extraction','patient-conditions-tooth-loss'),
  ('traumatic-tooth-loss','patient-conditions-tooth-loss'),
  ('denture-dissatisfaction','patient-conditions-tooth-loss'),
  ('alveolar-bone-loss','patient-conditions-bone'),
  ('vertical-bone-deficiency','patient-conditions-bone'),
  ('horizontal-bone-deficiency','patient-conditions-bone'),
  ('maxillary-sinus-proximity','patient-conditions-bone'),
  ('dental-caries','patient-conditions-bone'),
  ('white-spot-lesion','patient-conditions-bone'),
  ('root-caries','patient-conditions-bone'),
  ('dental-abscess','patient-conditions-bone'),
  ('bruxism','patient-conditions-bone'),
  ('tmj-disorder','patient-conditions-bone'),
  ('halitosis','patient-conditions-bone'),
  ('xerostomia','patient-conditions-bone'),
  ('tooth-fracture','patient-conditions-bone'),
  ('dry-socket','patient-conditions-bone'),
  ('pregnancy-gingivitis','patient-conditions-bone'),
  ('digital-smile-design','smile-design-cosmetic'),
  ('dental-veneer','smile-design-cosmetic'),
  ('porcelain-veneer','smile-design-cosmetic'),
  ('teeth-whitening','smile-design-cosmetic'),
  ('dental-crown','smile-design-cosmetic'),
  ('zirconia-crown','smile-design-cosmetic'),
  ('gold-crown','smile-design-cosmetic'),
  ('soft-tissue-management','gum-soft-tissue'),
  ('gum-contouring','gum-soft-tissue'),
  ('connective-tissue-graft','gum-soft-tissue'),
  ('peri-implant-mucosa','gum-soft-tissue'),
  ('keratinized-mucosa','gum-soft-tissue'),
  ('strip-graft','gum-soft-tissue'),
  ('ice-berg-technique','gum-soft-tissue'),
  ('garage-technique','gum-soft-tissue'),
  ('vipct','gum-soft-tissue'),
  ('caf','gum-soft-tissue'),
  ('tunneling-technique','gum-soft-tissue'),
  ('vista-technique','gum-soft-tissue'),
  ('tcaf','gum-soft-tissue'),
  ('black-triangle','gum-soft-tissue'),
  ('gingivitis','periodontics-perio-disease'),
  ('periodontitis','periodontics-perio-disease'),
  ('gum-recession','periodontics-perio-disease'),
  ('peri-implantitis','periodontics-perio-disease'),
  ('peri-implantitis-treatment','periodontics-perio-disease'),
  ('implantoplasty','periodontics-perio-disease'),
  ('regenerative-peri-implantitis-surgery','periodontics-perio-disease'),
  ('resective-peri-implantitis-surgery','periodontics-perio-disease'),
  ('dental-laser-therapy','periodontics-perio-disease'),
  ('clear-aligner','clear-aligner-orthodontics'),
  ('trioclear-aligner','clear-aligner-orthodontics'),
  ('damon-system','clear-aligner-orthodontics'),
  ('malocclusion','clear-aligner-orthodontics'),
  ('ortho-implant-sequencing','clear-aligner-orthodontics'),
  ('orthognathic-surgery','clear-aligner-orthodontics'),
  ('passive-self-ligating','clear-aligner-orthodontics'),
  ('direct-print-clear-aligner','clear-aligner-orthodontics'),
  ('in-house-aligner-lab','clear-aligner-orthodontics'),
  ('photopolymer-resin-tc85','clear-aligner-orthodontics'),
  ('aligner-attachment','clear-aligner-orthodontics'),
  ('3d-printer-aligner','clear-aligner-orthodontics'),
  ('thermoformed-aligner','clear-aligner-orthodontics'),
  ('orthodontic-treatment','clear-aligner-orthodontics'),
  ('root-canal-treatment','general-restorative'),
  ('tooth-extraction','general-restorative'),
  ('wisdom-tooth-removal','general-restorative'),
  ('dental-filling','general-restorative'),
  ('removable-denture','general-restorative'),
  ('torus-removal','general-restorative'),
  ('alveoloplasty','general-restorative'),
  ('tuberectomy','general-restorative'),
  ('dental-scaling','general-restorative'),
  ('frenectomy','general-restorative'),
  ('oral-pathology','general-restorative'),
  ('cbct-3d-scan','digital-technology-diagnostics'),
  ('digital-implant-planning','digital-technology-diagnostics'),
  ('surgical-guide','digital-technology-diagnostics'),
  ('intraoral-scanner','digital-technology-diagnostics'),
  ('cad-cam','digital-technology-diagnostics'),
  ('acteon-cbct','digital-technology-diagnostics'),
  ('trios-intraoral-scanner','digital-technology-diagnostics'),
  ('airflow-air-polishing','digital-technology-diagnostics'),
  ('cool-light-whitening-unit','digital-technology-diagnostics'),
  ('titanium','implant-materials'),
  ('zirconia','implant-materials'),
  ('bone-graft-substitute','implant-materials'),
  ('ptfe-membrane','implant-materials'),
  ('prf-platelet-rich-fibrin','implant-materials'),
  ('alveolar-bone','dental-anatomy'),
  ('mandible','dental-anatomy'),
  ('maxilla','dental-anatomy'),
  ('dental-implant-components','dental-anatomy'),
  ('maxillary-sinus','dental-anatomy'),
  ('pediatric-dentistry','pediatric-dentistry'),
  ('pediatric-pulpotomy','pediatric-dentistry'),
  ('pediatric-crown','pediatric-dentistry'),
  ('fluoride-treatment','pediatric-dentistry'),
  ('pit-fissure-sealant','pediatric-dentistry'),
  ('space-maintainer','pediatric-dentistry'),
  ('behavior-management','pediatric-dentistry'),
  ('early-orthodontic-intervention','pediatric-dentistry'),
  ('habit-appliance','pediatric-dentistry'),
  ('pediatric-extraction','pediatric-dentistry'),
  ('endodontic-microscope','endodontics-specialist'),
  ('root-canal-retreatment','endodontics-specialist'),
  ('apicoectomy','endodontics-specialist'),
  ('internal-bleaching','endodontics-specialist'),
  ('cracked-tooth','endodontics-specialist'),
  ('pulp-regeneration','endodontics-specialist'),
  ('rotary-endodontic-system','endodontics-specialist'),
  ('conscious-sedation','dental-anesthesia'),
  ('ga-dentistry','dental-anesthesia'),
  ('iv-sedation','dental-anesthesia'),
  ('dental-anxiety','dental-anesthesia'),
  ('geriatric-dentistry','demographic-dentistry'),
  ('pregnancy-dental-care','demographic-dentistry'),
  ('medical-compromised-dentistry','demographic-dentistry'),
  ('bedridden-dentistry','demographic-dentistry'),
  ('medical-clearance-protocol','demographic-dentistry'),
  ('special-needs-dentistry','demographic-dentistry'),
  ('social-security-dental-benefit','insurance-coverage-th'),
  ('sso-direct-billing-q-clinic','insurance-coverage-th'),
  ('universal-coverage-th','insurance-coverage-th'),
  ('civil-servant-dental-benefit','insurance-coverage-th'),
  ('private-dental-insurance-th','insurance-coverage-th'),
  ('smilescape-dental-clinic','brand-doctor-authority'),
  ('dr-woraphat-jarangkul','brand-doctor-authority'),
  ('smile-dna','brand-doctor-authority'),
  ('family-standard','brand-doctor-authority'),
  ('lifetime-implant-warranty','brand-doctor-authority'),
  ('smilescape-rattanathibet','brand-doctor-authority'),
  ('smilescape-srinakarin','brand-doctor-authority'),
  ('zero-bone-loss-concept','brand-doctor-authority'),
  ('dr-tomas-linkevicius','brand-doctor-authority'),
  ('dr-pitchapa-phudphong','brand-doctor-authority'))
update public.seo_website_page_master p set cluster_id = m.ss_cluster
from ssmap m
where p.page_fingerprint like 'smilescape-%'
  and p.primary_entity_fp = m.fp
  and p.cluster_id is distinct from m.ss_cluster;

-- validation
select count(*) ss_pages,
  count(*) filter (where cluster_id in (select cluster_slug from public.seo_topic_cluster_master
    where load_source like 'smile-scape-clinic:%' or cluster_slug='pediatric-dentistry')) on_ss_cluster,
  count(*) filter (where cluster_id is null) no_cluster
from public.seo_website_page_master where page_fingerprint like 'smilescape-%';
