-- 24_keyword_entity_binding.sql — Wave 14: bind DFS-enriched keywords to entities/pages, recompute tier. 2026-07-16.
--
-- CONTEXT: Operator ran the DFS full keyword batch (all 525 seed keywords enriched with
-- volume/CPC/competition/priority in seo_x_ads_keywords_monthly_market_snapshot — Stage 1 Gate data
-- was ready). This wave connects that data to entities and pages: DFS gives METRICS, this wave gives
-- RELEVANCE (which page each keyword actually belongs to).
--
-- METHOD (operator-directed, relevance-first): mapping is grounded in
-- content-plan/keyword-seed-list.md — the operator's own cluster/subgroup -> sitemap-anchor structure —
-- NOT in raw alias/volume fuzzy-matching (auto-alias-match alone only covered 100/525 = 19%). Rule:
-- "sitemap structure is the source of truth for what a page is about; a keyword's relevance to that
-- structure decides its entity, not its search volume" — so pages keep their keyword-independent
-- (DR-022 volume-immune) identity even where matched volume is 0.
--
-- EXCLUSIONS (operator-approved):
--   - Osstem/Dentium (cluster 5C): discontinued per SS-DR-001 (Neodent replaced Osstem in the implant
--     lineup). Comparison-content keywords (e.g. "blue diamond vs osstem") kept under their subject brand.
--   - "Other Aligner Brands" (cluster 6D — zenyum, clearcorrect, spark aligner): operator said take out
--     entirely, no comparison content planned. 6 keywords left with primary_entity_fp = NULL by design.
--   - Cluster 16 (geo-modifier templates "[service] กรุงเทพ" etc.): not real keywords, skipped at parse.
--
-- DISCOVERY: DFS's actual 525-keyword set included a 10-keyword "Neodent" cluster NOT present in the
-- original seed-list.md (operator hadn't anticipated market search volume for it). Mapped to
-- neodent-implant (entity already exists — SS-DR-001 successor brand to Osstem).
--
-- RESULT: 519/525 keywords bound to an entity (Wave 14a) -> 67 anchor pages get target_keyword_fp
-- (Wave 14b, one anchor page per entity — see de-dup note) -> 21 sitemap nodes promoted by tier
-- recompute (Wave 14c, promote-only vs the existing structural floor, never demoted).
--
-- Idempotent overall (values are deterministic), but note Wave 14b resets target_keyword_fp/
-- semantic_keywords_fps for ALL SmileScape pages before reassigning (required due to the UNIQUE
-- constraint on target_keyword_fp — an entity can have many pages, only one may hold the "anchor" slot).

-- ============================================================
-- Wave 14a — keyword -> entity (primary_entity_fp)
-- ============================================================
with m(kw, ent) as (values
('รากฟันเทียม','dental-implant'),
('รากฟันเทียม ราคา','dental-implant'),
('รากฟันเทียม ราคาถูก','dental-implant'),
('รากฟันเทียม ราคา 2026','dental-implant'),
('รากฟันเทียม ดีไหม','dental-implant'),
('รากฟันเทียม คืออะไร','dental-implant'),
('รากฟันเทียม ขั้นตอน','dental-implant'),
('รากฟันเทียม กี่วัน','dental-implant'),
('รากฟันเทียม กี่เดือน','dental-implant'),
('รากฟันเทียม เจ็บไหม','dental-implant'),
('รากฟันเทียม อันตรายไหม','dental-implant'),
('รากฟันเทียม อยู่ได้กี่ปี','dental-implant'),
('รากฟันเทียม รับประกัน','dental-implant'),
('รากฟันเทียม ผ่อน','dental-implant'),
('รากฟันเทียม ผ่อน 0','dental-implant'),
('รากฟันเทียม ผ่อน 0 ไม่ใช้บัตร','dental-implant'),
('รากฟันเทียม โปรโมชั่น','dental-implant'),
('รากฟันเทียม โปร 29900','dental-implant'),
('รากฟันเทียม ฟรี consult','dental-implant'),
('รากฟันเทียม ที่ไหนดี','dental-implant'),
('รากฟันเทียม คลินิก','dental-implant'),
('รากฟันเทียม คลินิกที่ไหนดี','dental-implant'),
('ราคารากฟันเทียม 1 ซี่','dental-implant'),
('ราคารากเทียมทั้งปาก','dental-implant'),
('ปลูกรากฟัน','dental-implant'),
('ปลูกรากฟันเทียม','dental-implant'),
('ฟันรากเทียม','dental-implant'),
('รากเทียมทันตกรรม','dental-implant'),
('ทำรากฟันเทียม','dental-implant'),
('ทำรากเทียม','dental-implant'),
('ทำรากฟันเทียม ที่ไหนดี','dental-implant'),
('รากฟันเทียม 1 ซี่','single-tooth-implant'),
('รากฟันเทียม ฟันหน้า','single-tooth-implant'),
('รากฟันเทียม ฟันหลัง','single-tooth-implant'),
('รากฟันเทียม ฟันกราม','single-tooth-implant'),
('รากฟันเทียมฟันหน้า ราคา','single-tooth-implant'),
('ใส่รากฟันเทียม 1 ซี่','single-tooth-implant'),
('รากเทียมซี่เดียว','single-tooth-implant'),
('single tooth implant','single-tooth-implant'),
('รากฟันเทียม หลายซี่','multiple-implants'),
('รากฟันเทียม 2 ซี่ 3 ซี่','multiple-implants'),
('ทำรากฟันเทียม หลายซี่','multiple-implants'),
('implant bridge','implant-supported-bridge'),
('สะพานฟันบนรากเทียม','implant-supported-bridge'),
('implant supported bridge','implant-supported-bridge'),
('ผ่าตัดรากฟันเทียม','dental-implant'),
('ผ่ารากฟันเทียม','dental-implant'),
('ขั้นตอนการฝังรากฟันเทียม','dental-implant'),
('การฝังรากฟันเทียม','dental-implant'),
('ฝังรากฟันเทียม','dental-implant'),
('รากเทียม ขั้นตอน','dental-implant'),
('รากฟันเทียม ผ่าตัด','dental-implant'),
('ฝังรากเทียม กี่วันใส่ฟัน','dental-implant'),
('osseointegration คืออะไร','osseointegration'),
('รากเทียมยึดกับกระดูก กี่เดือน','dental-implant'),
('รากเทียม immediate load','immediate-loading'),
('ใส่ฟันชั่วคราวบนรากเทียม','immediate-loading'),
('รากฟันเทียม ดูแลอย่างไร','dental-implant'),
('ดูแลรากฟันเทียม','dental-implant'),
('รากฟันเทียม หลังผ่าตัด','dental-implant'),
('รากฟันเทียม กินอะไรได้','dental-implant'),
('รากฟันเทียม กินอะไรไม่ได้','dental-implant'),
('รากฟันเทียม บวมกี่วัน','dental-implant'),
('รากฟันเทียม ห้ามทำอะไร','dental-implant'),
('รากฟันเทียม สูบบุหรี่','dental-implant'),
('รากฟันเทียม กี่วันถึงปกติ','dental-implant'),
('ทำรากฟันเทียม ทำงานต่อได้ไหม','dental-implant'),
('รากฟันเทียม หลุด','dental-implant'),
('รากฟันเทียม โยก','dental-implant'),
('รากฟันเทียม ติดเชื้อ','dental-implant'),
('รากฟันเทียม อักเสบ','dental-implant'),
('รากเทียมเหงือกอักเสบ','dental-implant'),
('peri-implantitis','peri-implantitis'),
('รากฟันเทียม peri-implantitis','peri-implantitis'),
('รากฟันเทียม ปัญหา','dental-implant'),
('รากฟันเทียม fail','dental-implant'),
('รากฟันเทียม ไม่ติด','dental-implant'),
('รากฟันเทียม ใช้งานไม่ได้','dental-implant'),
('รากเทียมหลุดทำอย่างไร','dental-implant'),
('แก้ไขรากเทียมที่ล้มเหลว','dental-implant'),
('implant failure คืออะไร','dental-implant'),
('รากฟันเทียม vs สะพานฟัน','dental-implant'),
('รากฟันเทียม กับ ฟันปลอม','dental-implant'),
('รากฟันเทียม กับ สะพานฟัน อันไหนดี','dental-implant'),
('รากฟันเทียม ฟันปลอม ต่างกัน','dental-implant'),
('รากฟันเทียม vs ครอบฟัน','dental-implant'),
('ทำรากฟัน หรือ สะพานฟัน','dental-implant'),
('ฟันปลอมแบบไหนดี','dental-implant'),
('ฟันปลอมติดแน่น vs ถอดได้','dental-implant'),
('รากฟันเทียม คนสูงอายุ','dental-implant'),
('รากฟันเทียม คนแก่ 70 ปี','dental-implant'),
('รากฟันเทียม เบาหวาน','dental-implant'),
('รากฟันเทียม ความดัน','dental-implant'),
('รากฟันเทียม กระดูกพรุน','dental-implant'),
('รากฟันเทียม คนอายุน้อย','dental-implant'),
('รากฟันเทียม ตั้งครรภ์','dental-implant'),
('รากฟันเทียม ทำได้ไหม','dental-implant'),
('all on 4','all-on-4'),
('all on 4 คืออะไร','all-on-4'),
('all on 4 ราคา','all-on-4'),
('all on 4 ดีไหม','all-on-4'),
('all on 4 vs all on 6','all-on-6'),
('all on 6','all-on-6'),
('all on x','all-on-x'),
('all on x ราคา','all-on-x'),
('รากฟันเทียม all on 4','all-on-4'),
('รากฟันเทียมทั้งปาก','all-on-x'),
('รากฟันเทียม ทั้งปาก ราคา','all-on-x'),
('รากฟันเทียม ทั้งปาก กี่ตัว','all-on-x'),
('ฟันปลอมติดแน่นทั้งปาก','all-on-x'),
('ฟันปลอมบนรากเทียม','overdenture'),
('overdenture รากเทียม','overdenture'),
('รากเทียมรองรับฟันปลอม','overdenture'),
('implant supported denture','overdenture'),
('ทำฟันทั้งปาก ราคา','all-on-x'),
('ทำฟันทั้งปาก รากเทียม','all-on-x'),
('all on 4 immediate load','immediate-loading'),
('all on 4 ขั้นตอน','all-on-4'),
('all on 4 หลังผ่าตัด','all-on-4'),
('all on 4 ดูแล','all-on-4'),
('all on 4 อยู่ได้กี่ปี','all-on-4'),
('all on 4 ผ่อน','all-on-4'),
('zygomatic implant','zygomatic-implant'),
('รากเทียม zygomatic','zygomatic-implant'),
('ฟันบนรากเทียม','all-on-x'),
('ผ่ารากเทียมทั้งปาก กี่วัน','all-on-x'),
('all on 4 ใส่ฟันทันที','full-arch-immediate-loading'),
('ฟันใหม่ในวันเดียว','full-arch-immediate-loading'),
('teeth in a day','full-arch-immediate-loading'),
('same day implant','full-arch-immediate-loading'),
('ปลูกกระดูก','bone-grafting'),
('ปลูกกระดูกฟัน','bone-grafting'),
('ปลูกกระดูกเพื่อรากเทียม','bone-grafting'),
('ปลูกกระดูก ราคา','bone-grafting'),
('ปลูกกระดูก เจ็บไหม','bone-grafting'),
('ปลูกกระดูก กี่เดือน','bone-grafting'),
('bone graft คืออะไร','bone-grafting'),
('bone graft รากฟันเทียม','bone-grafting'),
('bone graft ราคา','bone-grafting'),
('gbr คืออะไร','guided-bone-regeneration'),
('guided bone regeneration','guided-bone-regeneration'),
('sausage technique','sausage-technique'),
('sausage technique คืออะไร','sausage-technique'),
('urban technique','sausage-technique'),
('รากเทียมกระดูกไม่พอ','bone-grafting'),
('กระดูกขากรรไกรไม่พอ','bone-grafting'),
('กระดูกฟันละลาย','bone-grafting'),
('กระดูกหายแล้วทำรากเทียม','bone-grafting'),
('รากฟันเทียม กระดูกบาง','bone-grafting'),
('ยกไซนัส','sinus-lift'),
('ยกพื้นไซนัส','sinus-lift'),
('sinus lift คืออะไร','sinus-lift'),
('sinus lift ราคา','sinus-lift'),
('sinus lift เจ็บไหม','sinus-lift'),
('sinus lift กี่วันหาย','sinus-lift'),
('ยกไซนัส รากฟันเทียม','sinus-lift'),
('รากฟันเทียม ฟันบน ยกไซนัส','sinus-lift'),
('รากฟันเทียม ฟันกรามบน','sinus-lift'),
('internal sinus lift','internal-sinus-lift'),
('external sinus lift','lateral-window-sinus-lift'),
('direct sinus lift','lateral-window-sinus-lift'),
('indirect sinus lift','lateral-window-sinus-lift'),
('prf คืออะไร','prf-platelet-rich-fibrin'),
('platelet rich fibrin','prf-platelet-rich-fibrin'),
('prf รากฟันเทียม','prf-platelet-rich-fibrin'),
('prf ปลูกกระดูก','prf-platelet-rich-fibrin'),
('i-prf','prf-platelet-rich-fibrin'),
('a-prf','prf-platelet-rich-fibrin'),
('ปลูกเหงือก','soft-tissue-management'),
('ปลูกเหงือก ราคา','soft-tissue-management'),
('gum graft','soft-tissue-management'),
('soft tissue graft','soft-tissue-management'),
('ปลูกเหงือกรอบรากเทียม','soft-tissue-management'),
('เหงือกร่น','gum-recession'),
('เหงือกร่น แก้','gum-recession'),
('เหงือกร่น รักษา','gum-recession'),
('gingival recession','gum-recession'),
('free gingival graft','strip-graft'),
('fgg','strip-graft'),
('connective tissue graft','connective-tissue-graft'),
('ctg','connective-tissue-graft'),
('รากเทียม เหงือกสวย','gum-contouring'),
('รากเทียม เหงือกร่น','gum-recession'),
('รากเทียม ฟันหน้า เหงือกสวย','gum-contouring'),
('gum aesthetic implant','gum-contouring'),
('ปั้นเหงือก','gum-contouring'),
('แต่งเหงือก','gum-contouring'),
('gummy smile รักษา','gum-contouring'),
('ยิ้มเห็นเหงือก แก้','gum-contouring'),
('blue diamond implant','blue-diamond-implant'),
('blue diamond รากฟันเทียม','blue-diamond-implant'),
('blue diamond คืออะไร','blue-diamond-implant'),
('blue diamond ดีไหม','blue-diamond-implant'),
('blue diamond ราคา','blue-diamond-implant'),
('blue diamond รับประกัน','blue-diamond-implant'),
('blue diamond korea','blue-diamond-implant'),
('blue diamond vs straumann','blue-diamond-implant'),
('blue diamond vs osstem','blue-diamond-implant'),
('blue diamond รีวิว','blue-diamond-implant'),
('รากเทียม blue diamond','blue-diamond-implant'),
('รากเทียมเกาหลี blue diamond','blue-diamond-implant'),
('straumann','straumann-implant'),
('straumann implant','straumann-implant'),
('straumann รากฟันเทียม','straumann-implant'),
('straumann ราคา','straumann-implant'),
('straumann ดีไหม','straumann-implant'),
('straumann vs nobel biocare','straumann-implant'),
('straumann กับ blue diamond','straumann-implant'),
('straumann วาริสซิตี้','straumann-implant'),
('straumann slactive','straumann-implant'),
('รากเทียม straumann','straumann-implant'),
('รากเทียมสวิส straumann','straumann-implant'),
('ceramic implant','ceramic-implant'),
('รากฟันเทียมเซรามิก','ceramic-implant'),
('รากเทียมเซรามิก','ceramic-implant'),
('รากเทียมไม่ใช่โลหะ','ceramic-implant'),
('รากเทียม metal free','ceramic-implant'),
('รากเทียมเซรามิก ราคา','ceramic-implant'),
('รากเทียมเซรามิก ดีไหม','ceramic-implant'),
('รากเทียมเซรามิก vs ไทเทเนียม','ceramic-implant'),
('zirconia implant','ceramic-implant'),
('รากเทียม zirconia','ceramic-implant'),
('รากเทียมขาว','ceramic-implant'),
('รากฟันเทียมขาว','ceramic-implant'),
('แพ้โลหะ ทำรากเทียม','ceramic-implant'),
('รากเทียมฟันหน้า เซรามิก','ceramic-implant'),
('รากเทียมเกาหลี vs สวิส','dental-implant'),
('รากเทียมยี่ห้อไหนดี','dental-implant'),
('เปรียบเทียบรากเทียม','dental-implant'),
('รากเทียม brand','dental-implant'),
('รากเทียม ดีที่สุด','dental-implant'),
('รากเทียม korea ดีไหม','dental-implant'),
('รากเทียมยุโรป','dental-implant'),
('รากเทียม titanium vs ceramic','dental-implant'),
('จัดฟันใส','clear-aligner'),
('จัดฟันใส ราคา','clear-aligner'),
('จัดฟันใส ดีไหม','clear-aligner'),
('จัดฟันใส vs เหล็ก','clear-aligner'),
('จัดฟันใส กี่เดือน','clear-aligner'),
('จัดฟันใส เจ็บไหม','clear-aligner'),
('จัดฟันใสที่ไหนดี','clear-aligner'),
('จัดฟันใส ผ่อน','clear-aligner'),
('จัดฟันแบบใส','clear-aligner'),
('จัดฟันแบบโปร่งใส','clear-aligner'),
('clear aligner คืออะไร','clear-aligner'),
('ใส่จัดฟันแบบใส','clear-aligner'),
('จัดฟันโดยไม่ต้องติดเหล็ก','clear-aligner'),
('trioclear','trioclear-aligner'),
('trioclear คืออะไร','trioclear-aligner'),
('trioclear ดีไหม','trioclear-aligner'),
('trioclear ราคา','trioclear-aligner'),
('trioclear vs invisalign','trioclear-aligner'),
('trioclear vs zenyum','trioclear-aligner'),
('trioclear progressive','trioclear-aligner'),
('trioclear hk','trioclear-aligner'),
('modern dental trioclear','trioclear-aligner'),
('จัดฟัน trioclear','trioclear-aligner'),
('จัดฟันใส trioclear','trioclear-aligner'),
('trioclear รีวิว','trioclear-aligner'),
('invisalign','thermoformed-aligner'),
('invisalign คืออะไร','thermoformed-aligner'),
('invisalign ราคา','thermoformed-aligner'),
('invisalign ดีไหม','thermoformed-aligner'),
('invisalign กับ trioclear','thermoformed-aligner'),
('invisalign กี่เดือน','thermoformed-aligner'),
('invisalign vs braces','thermoformed-aligner'),
('invisalign full','thermoformed-aligner'),
('invisalign express','thermoformed-aligner'),
('invisalign express ราคา','thermoformed-aligner'),
('จัดฟัน invisalign','thermoformed-aligner'),
('จัดฟัน','orthodontic-treatment'),
('จัดฟันเหล็ก','orthodontic-treatment'),
('จัดฟันเหล็ก ราคา','orthodontic-treatment'),
('จัดฟันเหล็ก กี่เดือน','orthodontic-treatment'),
('จัดฟันเหล็ก vs ใส','orthodontic-treatment'),
('จัดฟัน damon','damon-system'),
('damon system','damon-system'),
('damon braces','damon-system'),
('self ligating braces','passive-self-ligating'),
('จัดฟัน self-ligating','passive-self-ligating'),
('จัดฟัน self ligating ดีไหม','passive-self-ligating'),
('จัดฟันด้านใน','orthodontic-treatment'),
('จัดฟันด้านใน ราคา','orthodontic-treatment'),
('lingual braces','orthodontic-treatment'),
('จัดฟันใส่ยาง','orthodontic-treatment'),
('จัดฟันยางสี','orthodontic-treatment'),
('จัดฟันเด็ก','early-orthodontic-intervention'),
('จัดฟันผู้ใหญ่','orthodontic-treatment'),
('จัดฟัน อายุเท่าไหร่','orthodontic-treatment'),
('จัดฟันบางส่วน','orthodontic-treatment'),
('ค่าจัดฟัน','orthodontic-treatment'),
('ค่าจัดฟันเหล็ก','orthodontic-treatment'),
('ผ่อนจัดฟัน','orthodontic-treatment'),
('จัดฟันที่ไหนดี','orthodontic-treatment'),
('วีเนียร์','dental-veneer'),
('วีเนียร์ ราคา','dental-veneer'),
('วีเนียร์ ดีไหม','dental-veneer'),
('วีเนียร์ กี่ซี่','dental-veneer'),
('วีเนียร์ ติดทน','dental-veneer'),
('วีเนียร์เซรามิก','porcelain-veneer'),
('วีเนียร์คอมโพสิต','dental-veneer'),
('ceramic veneer','porcelain-veneer'),
('composite veneer','dental-veneer'),
('emax veneer','porcelain-veneer'),
('veneer ราคา','dental-veneer'),
('veneer ปะหน้าฟัน','dental-veneer'),
('ปะหน้าฟัน','dental-veneer'),
('ปิดช่องว่างฟัน','dental-veneer'),
('ฟันห่าง แก้','dental-veneer'),
('ฟันบิ่น แก้','dental-veneer'),
('ฟอกฟันขาว','teeth-whitening'),
('ฟอกฟันขาว ราคา','teeth-whitening'),
('ฟอกฟันขาว ที่ไหนดี','teeth-whitening'),
('zoom whitening','teeth-whitening'),
('laser teeth whitening','teeth-whitening'),
('home bleaching','teeth-whitening'),
('fast bleaching','teeth-whitening'),
('ออกแบบรอยยิ้ม','digital-smile-design'),
('smile design','digital-smile-design'),
('smile makeover','digital-smile-design'),
('digital smile design','digital-smile-design'),
('dsd','digital-smile-design'),
('crown ครอบฟัน','dental-crown'),
('ครอบฟัน ราคา','dental-crown'),
('ครอบฟัน เซรามิก','dental-crown'),
('ครอบฟัน zirconia','zirconia-crown'),
('ครอบฟันสวยๆ','dental-crown'),
('hollywood smile','digital-smile-design'),
('ทำฟันสวย','digital-smile-design'),
('ฟันสวย รอยยิ้มสวย','digital-smile-design'),
('ยิ้มสวย ฟันเรียง','digital-smile-design'),
('ขูดหินปูน','dental-scaling'),
('ขูดหินปูน ราคา','dental-scaling'),
('ขูดหินปูน กี่ปีครั้ง','dental-scaling'),
('ขูดหินปูน เจ็บไหม','dental-scaling'),
('อุดฟัน','dental-filling'),
('อุดฟัน ราคา','dental-filling'),
('อุดฟัน สี','dental-filling'),
('อุดฟัน composite','dental-filling'),
('อุดฟันเซรามิก','dental-filling'),
('inlay onlay','dental-filling'),
('ถอนฟัน','tooth-extraction'),
('ถอนฟัน ราคา','tooth-extraction'),
('ถอนฟัน เจ็บไหม','tooth-extraction'),
('ถอนฟันคุด','wisdom-tooth-removal'),
('ถอนฟันคุด ราคา','wisdom-tooth-removal'),
('ผ่าฟันคุด','wisdom-tooth-removal'),
('ผ่าฟันคุด ราคา','wisdom-tooth-removal'),
('ผ่าฟันคุด เจ็บไหม','wisdom-tooth-removal'),
('ผ่าฟันคุด พักกี่วัน','wisdom-tooth-removal'),
('ฟันคุด','wisdom-tooth-removal'),
('ฟันคุดต้องผ่าไหม','wisdom-tooth-removal'),
('ฟันคุดเอกซเรย์','wisdom-tooth-removal'),
('รักษารากฟัน','root-canal-treatment'),
('รักษารากฟัน ราคา','root-canal-treatment'),
('รักษารากฟัน เจ็บไหม','root-canal-treatment'),
('รักษารากฟัน กี่ครั้ง','root-canal-treatment'),
('root canal คืออะไร','root-canal-treatment'),
('root canal ราคา','root-canal-treatment'),
('endodontics','root-canal-treatment'),
('ครอบฟันหลังรักษาราก','root-canal-treatment'),
('รากฟันอักเสบ','root-canal-treatment'),
('หนองที่รากฟัน','root-canal-treatment'),
('ตรวจฟัน','dental-scaling'),
('ตรวจฟัน ฟรี','dental-scaling'),
('ตรวจฟันประจำปี','dental-scaling'),
('เคลือบฟลูออไรด์','fluoride-treatment'),
('เคลือบหลุมร่องฟัน','pit-fissure-sealant'),
('sealant ฟัน','pit-fissure-sealant'),
('โรคเหงือก','periodontitis'),
('โรคเหงือก รักษา','periodontitis'),
('โรคเหงือกอักเสบ','gingivitis'),
('periodontitis','periodontitis'),
('gingivitis','gingivitis'),
('รักษาโรคเหงือก','periodontitis'),
('รักษาโรคเหงือก ราคา','periodontitis'),
('รำมะนาด','periodontitis'),
('ปริทันต์','periodontitis'),
('ปริทันต์ รักษา','periodontitis'),
('ขูดหินปูนใต้เหงือก','dental-scaling'),
('scaling root planing','dental-scaling'),
('deep cleaning ฟัน','dental-scaling'),
('flap surgery','periodontitis'),
('periodontal surgery','periodontitis'),
('ผ่าตัดเหงือก','periodontitis'),
('ปลูกกระดูกรักษาปริทันต์','periodontitis'),
('รากฟันเทียม โรคเหงือก','peri-implantitis'),
('peri-implantitis รักษา','peri-implantitis'),
('peri implantitis คืออะไร','peri-implantitis'),
('รากเทียม เหงือกอักเสบ','peri-implantitis'),
('ดูแลเหงือกรอบรากเทียม','peri-implantitis-treatment'),
('เหงือกบวม รากเทียม','peri-implantitis'),
('mucositis รากเทียม','peri-implantitis'),
('ทันตกรรมเด็ก','pediatric-dentistry'),
('หมอฟันเด็ก','pediatric-dentistry'),
('ทันตแพทย์เด็ก','pediatric-dentistry'),
('ฟันเด็ก','pediatric-dentistry'),
('ฟันน้ำนม','pediatric-dentistry'),
('ฟันน้ำนมผุ','pediatric-dentistry'),
('ฟันแท้ขึ้น','pediatric-dentistry'),
('ตรวจฟันเด็ก','dental-scaling'),
('อุดฟันเด็ก','dental-filling'),
('ถอนฟันน้ำนม','tooth-extraction'),
('เคลือบฟลูออไรด์เด็ก','fluoride-treatment'),
('เคลือบหลุมร่องฟันเด็ก','pit-fissure-sealant'),
('จัดฟันเด็ก กี่ขวบ','early-orthodontic-intervention'),
('ฟันเด็กผุ','pediatric-dentistry'),
('ดูแลฟันเด็ก','pediatric-dentistry'),
('ลูกฟันผุ ทำอย่างไร','pediatric-dentistry'),
('ฟันลูกห่าง','pediatric-dentistry'),
('ค่าทำฟัน','smilescape-dental-clinic'),
('ค่ารากฟันเทียม','dental-implant'),
('ราคาทำฟัน','smilescape-dental-clinic'),
('ราคาทำฟันถูก','smilescape-dental-clinic'),
('ผ่อน 0 ทำฟัน','smilescape-dental-clinic'),
('ผ่อนทำฟัน ไม่ใช้บัตร','smilescape-dental-clinic'),
('ผ่อนรากฟันเทียม','dental-implant'),
('ประกันสังคม ทำฟัน','social-security-dental-benefit'),
('ประกันสังคม ขูดหินปูน','social-security-dental-benefit'),
('ประกันสังคม อุดฟัน','dental-filling'),
('ประกันสังคม ถอนฟัน','tooth-extraction'),
('ประกันสังคม รากฟันเทียม','social-security-dental-benefit'),
('สิทธิประกันสังคม ทันตกรรม','social-security-dental-benefit'),
('ใช้ประกันสังคม ทำฟัน ที่ไหน','social-security-dental-benefit'),
('ทำฟัน 900 ประกันสังคม','social-security-dental-benefit'),
('ทำฟัน 900 ที่ไหน','social-security-dental-benefit'),
('ทำฟันใช้สิทธิ์ได้ที่ไหน','social-security-dental-benefit'),
('สิทธิ์ทันตกรรม ประกันสังคม','social-security-dental-benefit'),
('ประกันสุขภาพ ทำฟัน','private-dental-insurance-th'),
('ทำฟันใช้ประกัน','private-dental-insurance-th'),
('ค่ารักษาฟัน ลดหย่อนภาษี','smilescape-dental-clinic'),
('ภาษี ทำฟัน','smilescape-dental-clinic'),
('กลัวทำฟัน','dental-anxiety'),
('กลัวหมอฟัน','dental-anxiety'),
('phobia ทันตแพทย์','dental-anxiety'),
('dental phobia','dental-anxiety'),
('กลัวเข็ม ทำฟัน','dental-anxiety'),
('กลัวผ่าตัด รากฟันเทียม','dental-anxiety'),
('ทำฟัน ไม่เจ็บ','dental-anxiety'),
('รากฟันเทียม วางยา','conscious-sedation'),
('รากฟันเทียม ดมยา','conscious-sedation'),
('ทำฟันเด็กกลัว','dental-anxiety'),
('หาหมอฟันใจดี','dental-anxiety'),
('หมอฟันใจดี','dental-anxiety'),
('ทำฟันสบายๆ','dental-anxiety'),
('ทำฟันไม่กลัว','dental-anxiety'),
('ฉีดยาชา ทันตกรรม','dental-anxiety'),
('ฉีดยาชา ปวด','dental-anxiety'),
('ทำฟัน หลับสบาย','conscious-sedation'),
('รากฟันเทียม สลบ','conscious-sedation'),
('สอบถามก่อนทำ รากเทียม','dental-implant'),
('ขอ second opinion ทันตกรรม','dental-implant'),
('smilescape','smilescape-dental-clinic'),
('smilescape clinic','smilescape-dental-clinic'),
('smile scape','smilescape-dental-clinic'),
('smilescape dental','smilescape-dental-clinic'),
('smilescape รัตนาธิเบศร์','smilescape-dental-clinic'),
('smilescape ศรีนครินทร์','smilescape-dental-clinic'),
('smilescape โปรโมชั่น','smilescape-dental-clinic'),
('smilescape รากฟันเทียม','smilescape-dental-clinic'),
('smilescape pantip','smilescape-dental-clinic'),
('smilescape รีวิว','smilescape-dental-clinic'),
('สไมล์สเคป','smilescape-dental-clinic'),
('สไมล์สเคป คลินิก','smilescape-dental-clinic'),
('คลินิกสไมล์สเคป','smilescape-dental-clinic'),
('หมอแฮม smilescape','dr-woraphat-jarangkul'),
('ทพ. วรภัทร จรางกุล','dr-woraphat-jarangkul'),
('หมอแฮม รากฟันเทียม','dr-woraphat-jarangkul'),
('รากฟันเทียม by smilescape','smilescape-dental-clinic'),
('ทำฟัน รัตนาธิเบศร์','smilescape-rattanathibet'),
('รากฟันเทียม รัตนาธิเบศร์','smilescape-rattanathibet'),
('รากฟันเทียม นนทบุรี','smilescape-rattanathibet'),
('รากเทียม นนทบุรี','smilescape-rattanathibet'),
('จัดฟัน รัตนาธิเบศร์','smilescape-rattanathibet'),
('จัดฟัน นนทบุรี','smilescape-rattanathibet'),
('คลินิกทันตกรรม รัตนาธิเบศร์','smilescape-rattanathibet'),
('คลินิกทันตกรรม นนทบุรี','smilescape-rattanathibet'),
('หมอฟัน รัตนาธิเบศร์','smilescape-rattanathibet'),
('ทำฟัน mrt สีม่วง','smilescape-rattanathibet'),
('รากเทียม mrt รัตนาธิเบศร์','smilescape-rattanathibet'),
('ทำฟัน ศรีนครินทร์','smilescape-srinakarin'),
('รากฟันเทียม ศรีนครินทร์','smilescape-srinakarin'),
('รากฟันเทียม mrt สีเหลือง','smilescape-srinakarin'),
('จัดฟัน ศรีนครินทร์','smilescape-srinakarin'),
('คลินิกทันตกรรม ศรีนครินทร์','smilescape-srinakarin'),
('หมอฟัน ศรีนครินทร์','smilescape-srinakarin'),
('ทำฟัน mrt สีเหลือง','smilescape-srinakarin'),
('ทำฟัน บางกะปิ','smilescape-srinakarin'),
('ทำฟัน หัวหมาก','smilescape-srinakarin'),
('รากเทียม กรุงเทพ ตะวันออก','smilescape-srinakarin'),
('ct scan ฟัน','cbct-3d-scan'),
('ct scan ทันตกรรม','cbct-3d-scan'),
('3d x-ray ฟัน','cbct-3d-scan'),
('cone beam ct','cbct-3d-scan'),
('cbct','cbct-3d-scan'),
('intraoral scanner','intraoral-scanner'),
('digital impression','intraoral-scanner'),
('แสกนฟัน','intraoral-scanner'),
('ฟิลม์ดิจิทัล ทันตกรรม','digital-implant-planning'),
('ทำฟันดิจิทัล','digital-implant-planning'),
('digital dentistry','digital-implant-planning'),
('cad cam dental','cad-cam'),
('cad cam ครอบฟัน','cad-cam'),
('zirconia mill','cad-cam'),
('guided implant surgery','surgical-guide'),
('surgical guide รากเทียม','surgical-guide'),
('piezoelectric surgery','dental-laser-therapy'),
('piezo รากเทียม','dental-laser-therapy'),
('laser dental','dental-laser-therapy'),
('soft tissue laser','dental-laser-therapy'),
('diode laser ทันตกรรม','dental-laser-therapy'),
('ระบบฆ่าเชื้อ ทันตกรรม','smilescape-dental-clinic'),
('sterilization คลินิก','smilescape-dental-clinic'),
('autoclave ทันตกรรม','smilescape-dental-clinic'),
('class b autoclave','smilescape-dental-clinic'),
('blue diamond vs neodent','blue-diamond-implant'),
('neodent','neodent-implant'),
('neodent implant','neodent-implant'),
('neodent straumann group','neodent-implant'),
('neodent vs blue diamond','neodent-implant'),
('neodent ดีไหม','neodent-implant'),
('neodent รากฟันเทียม','neodent-implant'),
('neodent ราคา','neodent-implant'),
('รากเทียม neodent','neodent-implant'),
('รากเทียม neodent ราคา','neodent-implant')
),
upd as (
  update public.seo_x_ads_keywords_contextual_master k
  set primary_entity_fp = m.ent,
      primary_entity_name = g.entity_name
  from m join public.seo_entity_graph g on g.entity_fingerprint = m.ent
  where k.brand ilike '%smile%scape%'
    and lower(trim(k.keyword)) = m.kw
  returning k.fingerprint
)
select count(*) bound_14a from upd;

-- ============================================================
-- Wave 14b — keyword <-> page. One ANCHOR page per entity gets target_keyword_fp
-- (best-tier, shallowest-depth page owns the UNIQUE slot); all pages sharing that
-- entity get semantic_keywords_fps (the full/other keyword list). Also sets
-- ad_landing_page_fp on the top-priority keyword row per entity (reverse pointer).
-- ============================================================
update public.seo_website_page_master
set target_keyword_fp = null, semantic_keywords_fps = null
where page_fingerprint like 'smilescape-%';

with kw_by_ent as (
  select k.primary_entity_fp ent, k.fingerprint kw_fp,
    coalesce(s.seo_ads_priority_score,0) prio,
    row_number() over (partition by k.primary_entity_fp order by coalesce(s.seo_ads_priority_score,0) desc, k.keyword) rn
  from public.seo_x_ads_keywords_contextual_master k
  left join public.seo_x_ads_keywords_monthly_market_snapshot s on s.keyword=k.keyword and s.brand=k.brand
  where k.brand ilike '%smile%scape%' and k.primary_entity_fp is not null
),
ent_agg as (
  select ent,
    max(kw_fp) filter (where rn=1) top_kw,
    array_agg(kw_fp order by prio desc) filter (where rn>1) other_kw,
    array_agg(kw_fp order by prio desc) all_kw
  from kw_by_ent group by ent
),
anchor_page as (
  select distinct on (p.primary_entity_fp) p.primary_entity_fp ent, p.page_fingerprint anchor_fp
  from public.seo_website_page_master p
  where p.page_fingerprint like 'smilescape-%' and p.primary_entity_fp is not null
  order by p.primary_entity_fp,
    case p.node_tier when 'A' then 1 when 'B' then 2 when 'C' then 3 when 'D' then 4 else 5 end,
    coalesce(p.crawl_depth,9), p.sitemap_node_id
)
update public.seo_website_page_master p
set target_keyword_fp = case when ap.anchor_fp = p.page_fingerprint then e.top_kw else null end,
    semantic_keywords_fps = case when ap.anchor_fp = p.page_fingerprint then e.other_kw else e.all_kw end
from ent_agg e
join anchor_page ap on ap.ent = e.ent
where p.page_fingerprint like 'smilescape-%' and p.primary_entity_fp = e.ent;

with best_kw as (
  select k.fingerprint kw_fp, k.primary_entity_fp ent,
    coalesce(s.seo_ads_priority_score,0) prio,
    row_number() over (partition by k.primary_entity_fp order by coalesce(s.seo_ads_priority_score,0) desc, k.keyword) rn
  from public.seo_x_ads_keywords_contextual_master k
  left join public.seo_x_ads_keywords_monthly_market_snapshot s on s.keyword=k.keyword and s.brand=k.brand
  where k.brand ilike '%smile%scape%' and k.primary_entity_fp is not null
)
update public.seo_x_ads_keywords_contextual_master k
set ad_landing_page_fp = p.page_fingerprint
from best_kw b
join public.seo_website_page_master p on p.page_fingerprint like 'smilescape-%' and p.primary_entity_fp = b.ent
where k.fingerprint = b.kw_fp and b.rn = 1;

-- ============================================================
-- Wave 14c — tier recompute. PROMOTE-ONLY vs the existing structural floor
-- (DR-022 volume-immune: sitemap-derived tier never demoted by a keyword signal).
-- A if anchor keyword priority>=80, B if >=60, else keep the structural floor.
-- ============================================================
with page_signal as (
  select p.page_fingerprint, p.node_tier floor_tier,
    coalesce(
      (select s.seo_ads_priority_score from public.seo_x_ads_keywords_contextual_master k
        join public.seo_x_ads_keywords_monthly_market_snapshot s on s.keyword=k.keyword and s.brand=k.brand
        where k.fingerprint = p.target_keyword_fp),
      0) prio
  from public.seo_website_page_master p
  where p.page_fingerprint like 'smilescape-%'
),
new_tier as (
  select page_fingerprint,
    case when prio >= 80 then 'A' when prio >= 60 then 'B' else floor_tier end computed_tier,
    floor_tier
  from page_signal
)
update public.seo_website_page_master p
set node_tier = n.computed_tier
from new_tier n
where p.page_fingerprint = n.page_fingerprint
  and n.computed_tier <> n.floor_tier and n.computed_tier < n.floor_tier;  -- 'A'<'B'<'C'<'D' lexically = better-first

-- validation
select
 (select count(*) from public.seo_x_ads_keywords_contextual_master where brand ilike '%smile%scape%' and primary_entity_fp is not null) kw_bound,
 (select count(*) from public.seo_website_page_master where page_fingerprint like 'smilescape-%' and target_keyword_fp is not null) pages_anchored,
 (select count(*) from public.seo_website_page_master where page_fingerprint like 'smilescape-%' and semantic_keywords_fps is not null) pages_with_semantic,
 (select jsonb_object_agg(node_tier,c) from (select node_tier, count(*) c from public.seo_website_page_master where page_fingerprint like 'smilescape-%' group by 1) x) tier_dist;
